// Generated by https://quicktype.io

export interface Replay {
  map: Map;
  playerId: number;
  date: string;
  version: Version;
  server: Server;
  players: Player[];
}

export interface Map {
  name: string;
  displayName: string;
}

export interface Player {
  id: number;
  name: string;
  vehicle: Vehicle;
}

export interface Vehicle {
  nation: string;
  name: string;
}

export interface Server {
  name: string;
  regionCode: string;
}

export interface Version {
  executable: string;
  xml: string;
}
